### ISSUE TITLE
calculateWinner failes in the last move

### ISSUE THREAD

**Issue by gbartosz** [harman052/react-tutorial-solutions#1]
calculateWinner fails to point that X won in the last possible move.
Situation before last move:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/4162881/86726490-e583c900-c02a-11ea-9ac8-7f039fb7a4f7.png">
Expected result:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/4162881/86726535-ef0d3100-c02a-11ea-9f0a-c944df609e93.png">
What actually happens:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/4162881/86726620-051af180-c02b-11ea-83e2-8ea883dedd88.png">

Proposed solution:
replace
```
for (let i = 0; i < lines.length; i++) {
  const [a, b, c] = lines[i];
  if (
    squares[a] &&
    squares[a] === squares[b] &&
    squares[a] === squares[c]
  ) {
    result = {
      status: "win",
      win: { player: squares[a], squares: [a, b, c] }
    };
    return result;
  } else {
    let tempSq = squares.filter(item => item === null);
    if (tempSq.length === 0) {
      result = { status: "draw", win: {} };
      return result;
    }
  }
}
```
with
```
for (let i = 0; i < lines.length; i++) {
  const [a, b, c] = lines[i];
  if (
    squares[a] &&
    squares[a] === squares[b] &&
    squares[a] === squares[c]
  ) {
    result = {
      status: "win",
      win: { player: squares[a], squares: [a, b, c] }
    };
    return result;
  } 
}
let tempSq = squares.filter(item => item === null);
if (tempSq.length === 0) {
  result = { status: "draw", win: {} };
  return result;
}
```

**Comment by harman052** [comment]
Thanks @gbartosz for catching this bug. I pushed the fix. 👍
